### ISSUE TITLE
FAQ clarifications

### ISSUE THREAD

**Issue by 8vitagen** [TheOfficialFloW/modoru#12]
Simple additions. Firstly, unlinking the memory card should be added to the steps since downgrading can otherwise make it unuseable. Secondly, while there generally isn't a need to use it on such a system, can you clarify that downgrading a system updated via update365 is OK?

**Comment by CelesteBlue-dev** [comment]
1) no need because modoru removes id.dat automatically before launching the downgrade.
2) a system updated via update365 is nothing special.

**Comment by 8vitagen** [comment]
That's odd, because apparently there are people running into the firmware wall after downgrading, [example on r/VitaHacks](https://www.reddit.com/r/vitahacks/comments/argin6/after_using_modoru_im_stuxk_at_this_trying_to/) but maybe it's a different issue. Also thanks for clarification on 2.
