### ISSUE TITLE
Vita in bootloop

### ISSUE THREAD

**Issue by scullys** [TheOfficialFloW/modoru#14]
I used the wrong file (factory was 3.65, but the target was 3.60) and now my Vita is stuck in a bootloop. Is my Vita permanently bricked? I’ve tried resetting and trying everything on safe mode but it doesn’t do anything.

**Comment by TheOfficialFloW** [comment]
modoru should prevent you from downgrading to a lower version than the factory version.

**Comment by scullys** [comment]
is there anything i can do? i tried all options on safe mode to no avail.

**Comment by TheOfficialFloW** [comment]
Hold L while booting...

**Comment by scullys** [comment]
after realizing my mistake i realize that i quit the app, but it continued with updating

**Comment by scullys** [comment]
holding L doesn't do anything either

**Comment by TheOfficialFloW** [comment]
Please explain your situation again. Did you abort the update process (while in the green app)? Do you see the logo when booting up, does the PS button show blue?

**Comment by scullys** [comment]
The update was on the green app, I was holding the power button down in an attempt to cancel it. The PS Button does not flash blue when it boots up.

**Comment by TheOfficialFloW** [comment]
Well that‘s your fault, for sure the console will brick if you power off while updating. Your factory firmware wasn‘t 3.65 then, otherwise it wouldn‘t have been possible to start the update. Good job bricking your console because of your fear of bricking it.
