### ISSUE TITLE
3.70 Vita won't downgrade

### ISSUE THREAD

**Issue by LegoLeonidas** [TheOfficialFloW/modoru#16]
Vita model 2000 using internal memory. firmware is 3.70, with 3.09 factory firmware. Trinity and VitaShell are installed and working normally, plugins folders are renamed to disable them. Modoru is installed, with the 3.60 PUP file from the darthsternie site. Modoru indicates proper target firmware, acts like it is updating, but when the Vita restarts, it is still on 3.70. No error messages. I have reformatted memory, done a system restore, tried 3.65 firmware instead, redone the process from the ground up, nothing has worked

**Comment by TheOfficialFloW** [comment]
Make sure you usethe FULL version, not systemdata or pre.
