### ISSUE TITLE
readme.md doesn't clarify if you will lose data from downgrading

### ISSUE THREAD

**Issue by realNZZN** [TheOfficialFloW/modoru#23]
I can't find an answer (or even question) as to whether I will keep my games and saves, etc after downgrading

**Comment by p16774** [comment]
If you have a separate SD card, you can pull that out before downgrading and then rebuild the database after you are unlocked. You are reinstalling the base OS, so you will lose everything previously installed. If you have a new 2000 version Vita, you can also remove any Sony MemCard and again rebuild the database after, but you will need to go through an unlink process for that to work without formatting, I believe.

**Comment by p16774** [comment]
> I Can't find a straight answer (or even question) as to whether I will keep my games and saves anywhere

If you have a separate SD card, you can pull that out before downgrading and then rebuild the database after you are unlocked. You are reinstalling the base OS, so you will lose everything previously installed. If you have a new 2000 version Vita, you can also remove any Sony MemCard and again rebuild the database after, but you will need to go through an unlink process for that to work without formatting, I believe.

**Comment by realNZZN** [comment]
I Have a 2000, So if I install Modoru to internal storage and remove my SD Card while downgrading will my data on my card (games and saves) still work if i rebuild database? Going from 3.68 to 3.65 if that makes a difference

**Comment by p16774** [comment]
> I Have a 2000, So if I install Modoru to internal storage and remove my SD Card while downgrading will my data on my card (games and saves) still work if i rebuild database? Going from 3.68 to 3.65 if that makes a difference

You will have to set up your mounting again so it points to your SD card before rebuilding, but yes it should work that way. I would say, the benefits of the "always root" wasn't worth rebuilding everything for me. Having to run encore every time I restart was a smaller hindrance than having to reinstall and reconfigure all my plugins. Plus, you will have to install compatibility packs for all games that require a firmware higher than 3.65

**Comment by realNZZN** [comment]
update: Ended up having to downgrade a while ago and didn't lose any data, it installs like a normal system update and from what I can tell doesn't touch your user partitions. All my games and saves were still there.
