### ISSUE TITLE
FR - Minimum version display

### ISSUE THREAD

**Issue by rboninsegna** [TheOfficialFloW/modoru#3]
Hello, Andy!

Could it be possible to make Modoru display the lowest installable version without having to disable plugins first? Just for convenience :)

Thanks!

**Comment by StepS-** [comment]
Hi, I did this in #2 and this should be pushed to releases soon.

**Comment by southrop** [comment]
Correct me if I'm wrong, but I think that was just addressed in #2 2 or so hours ago so will probably be in the next version.

**Comment by rboninsegna** [comment]
Haha, great then!

Thanks in advance to you too!
