### ISSUE TITLE
50% battery life on older vitas

### ISSUE THREAD

**Issue by Yohoki** [TheOfficialFloW/modoru#5]
I've got an old 1st gen Vita and, well, like all old things it's got a battery that's failing, often showing low battery messages even after charging for hours, and showing the battery indicator at low% for a few seconds and then showing full again. Is this going to be an issue? From what I read on Wololo, the binary is hard-coded to not work if the battery shows less than 50%?

I guess what I should ask is does this battery% check only happen at launch, or will the power dipping below 50% for a few seconds cause any problems while the program is installing the downgrade?

Could it simply be plugged into the wall to mitigate this issue?

**Comment by Zmxhawrhbg** [comment]
hi, i enjoy worse solutions for things so have you tried the common fix for vita battery which is to disconnect and reconnect battery (while off) - this trick worked for me

it is hardcoded to error at less than 50%, however, it seems you can bypass this by [pressing the right trigger on load](https://github.com/TheOfficialFloW/modoru/blob/d717cd4ec831293d3c1d0a0bec65b92b47fa768e/main.c#L302)

power dipping won't cause a problem _unless_ it dips below 0 and dies during the downgrade, in which case your vita is up to the mercy of whatever the upgrader was doing at the time, if its plugged into a wall it shouldn't die

in any case i'd recommend a update file of your current firmware to be stored on the memory card for such cases where you have to reinstall system (put in ux0:data/PSP2/UPDATE/PSP2UPDAT.PUP), you can install that by removing the vita gamecard, booting into safe mode, and selecting update from vita card

read the code before running it smh....

**Comment by Yohoki** [comment]
Good to know! Thanks for the very informative answer!

**Comment by colto1000** [comment]
For those here in the *future*, when downgrading from 3.65 > 3.60, holding right trigger for bypass didn't work. I had to hold LEFT trigger, then while still holding it, swipe back over to the app, and start it (while *still* holding that left trigger).

I did this out of laziness when I was at 35% ish - maybe not smart, but it worked just fine for me as I was plugged into AC.
