### ISSUE TITLE
Error c2-12848-3

### ISSUE THREAD

**Issue by Peashy54** [TheOfficialFloW/modoru#7]
I keep getting this error when I try to downgrade from 3.68 to 3.65. How do I fix this?

**Comment by Yohoki** [comment]
Before running Modoru, did you run h-encore? I'm also going from 3.68 to 3.65 and had no issues running the app.

**Comment by Peashy54** [comment]
I do use h encore before cause I wouldn't be able to use the downgrader if I didn't.... The error comes up at the point when the 3.65/3.60 update would go to run and install. I honestly don't know why I'm getting the error.... I've done all the steps correctly I think I've renamed the tai folders and placed the update in the correct spot so I don't know what's going wrong....

**Comment by FormerNoob** [comment]
The readme said we should rename the config.txt, not the tai folder, in my view.

**Comment by Peashy54** [comment]
Either way it seems my issue might just lie with the internal drivers themselves.... The downgrader runs up until the part when the update is supposed to run

**Comment by Peashy54** [comment]
Please reopen I wasn't aware that the close and comment would close the topic.

**Comment by silentcovenant** [comment]
When trying to install with Vitashell, I get this error: 0x80871007

**Comment by TheOfficialFloW** [comment]
Please reinstall h-encore 2.0.

**Comment by silentcovenant** [comment]
I did an upgrade from the previous version of h-encore. It seems to have worked, do I need to uninstall/reinstall?
