### ISSUE TITLE
ux0 questions & problem

### ISSUE THREAD

**Issue by Brayton1234567** [TheOfficialFloW/modoru#8]
I can't fit the PSP2UPDATE on my ux0, I'm on a PS Vita TV, can I install it on the flash drive I use as a memory card and use it on that? I almost did, but I'll try to make space on ux0 to be safe.

**Comment by TheOfficialFloW** [comment]
No

**Comment by Brayton1234567** [comment]
Ok, just to mention, I use VitaShell to mount it as ux0.
